import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { startTransition, useDeferredValue, useState } from 'react';
import { useSession } from '../../use-session.js';

function formatMoney(amountMinor) {
  return `${(amountMinor / 100).toFixed(2)} SAR`;
}

function humanize(value) {
  return value.replaceAll('_', ' ');
}

export function OpsDashboardBoard() {
  const { api } = useSession();
  const [rangeDays, setRangeDays] = useState(7);
  const deferredRangeDays = useDeferredValue(rangeDays);
  const { data } = useQuery({
    queryKey: ['ops-dashboard-overview', deferredRangeDays],
    queryFn: () =>
      api.getOpsDashboardOverview({
        range_days: deferredRangeDays,
      }),
  });

  const dashboard = data;

  return (
    <section className="board panel">
      <div className="board-header">
        <div>
          <span className="eyebrow">Ops dashboard</span>
          <h2>Marketplace KPI view across orders, finance, and rider earnings</h2>
        </div>
        <span className="status-pill" data-tone="alert">
          {dashboard?.kpis.active_orders ?? 0} active orders
        </span>
      </div>

      <div className="toolbar">
        <select
          aria-label="Select ops dashboard range"
          onChange={(event) =>
            startTransition(() => setRangeDays(Number(event.target.value)))
          }
          value={rangeDays}
        >
          <option value={7}>Last 7 days</option>
          <option value={30}>Last 30 days</option>
        </select>
      </div>

      <div className="insight-strip">
        <div className="panel">
          <span className="eyebrow">Gross sales</span>
          <strong>{formatMoney(dashboard?.kpis.gross_sales_minor ?? 0)}</strong>
          <p>Non-cancelled order subtotal across the selected reporting window.</p>
        </div>
        <div className="panel">
          <span className="eyebrow">Platform net</span>
          <strong>{formatMoney(dashboard?.financials.net_platform_minor ?? 0)}</strong>
          <p>Commission plus adjustments, kept separate from merchant and rider liabilities.</p>
        </div>
        <div className="panel">
          <span className="eyebrow">Rider earnings</span>
          <strong>{formatMoney(dashboard?.rider_earnings.total_earnings_minor ?? 0)}</strong>
          <p>Total rider payout liability generated by delivered orders in range.</p>
        </div>
      </div>

      {dashboard ? (
        <div className="report-layout">
          <section className="panel">
            <div className="board-header">
              <div>
                <span className="eyebrow">KPI summary</span>
                <h3>Order and fleet health</h3>
              </div>
            </div>

            <dl className="report-stats">
              <div>
                <dt>Total orders</dt>
                <dd>{dashboard.kpis.total_orders}</dd>
              </div>
              <div>
                <dt>Delivered</dt>
                <dd>{dashboard.kpis.delivered_orders}</dd>
              </div>
              <div>
                <dt>Cancelled</dt>
                <dd>{dashboard.kpis.cancelled_orders}</dd>
              </div>
              <div>
                <dt>Active merchants</dt>
                <dd>{dashboard.kpis.active_merchants}</dd>
              </div>
              <div>
                <dt>Accepting branches</dt>
                <dd>{dashboard.kpis.accepting_branches}</dd>
              </div>
              <div>
                <dt>Available riders</dt>
                <dd>{dashboard.kpis.available_riders}</dd>
              </div>
            </dl>
          </section>

          <section className="panel">
            <div className="board-header">
              <div>
                <span className="eyebrow">Status breakdown</span>
                <h3>Order state mix</h3>
              </div>
            </div>

            <table className="report-table">
              <thead>
                <tr>
                  <th>Status</th>
                  <th>Count</th>
                </tr>
              </thead>
              <tbody>
                {dashboard.order_status_breakdown.map((status) => (
                  <tr key={status.status}>
                    <td>{humanize(status.status)}</td>
                    <td>{status.count}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>

          <section className="panel">
            <div className="board-header">
              <div>
                <span className="eyebrow">Merchant sales</span>
                <h3>Merchant ranking</h3>
              </div>
            </div>

            <table className="report-table">
              <thead>
                <tr>
                  <th>Merchant</th>
                  <th>Orders</th>
                  <th>Delivered</th>
                  <th>Gross sales</th>
                </tr>
              </thead>
              <tbody>
                {dashboard.merchant_sales.map((merchant) => (
                  <tr key={merchant.merchant_uuid ?? merchant.merchant_name}>
                    <td>{merchant.merchant_name}</td>
                    <td>{merchant.total_orders}</td>
                    <td>{merchant.delivered_orders}</td>
                    <td>{formatMoney(merchant.gross_sales_minor)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>

          <section className="panel">
            <div className="board-header">
              <div>
                <span className="eyebrow">Rider earnings</span>
                <h3>Payout exposure</h3>
              </div>
            </div>

            <table className="report-table">
              <thead>
                <tr>
                  <th>Rider</th>
                  <th>Deliveries</th>
                  <th>Earnings</th>
                  <th>Avg / delivery</th>
                </tr>
              </thead>
              <tbody>
                {dashboard.rider_earnings.riders.map((rider) => (
                  <tr key={rider.rider_uuid ?? rider.rider_name}>
                    <td>{rider.rider_name}</td>
                    <td>{rider.deliveries_count}</td>
                    <td>{formatMoney(rider.earnings_minor)}</td>
                    <td>{formatMoney(rider.average_per_delivery_minor)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>

          <section className="panel">
            <div className="board-header">
              <div>
                <span className="eyebrow">Daily trend</span>
                <h3>Order volume by day</h3>
              </div>
            </div>

            <table className="report-table">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Orders</th>
                  <th>Delivered</th>
                  <th>Gross sales</th>
                </tr>
              </thead>
              <tbody>
                {dashboard.daily_orders.map((day) => (
                  <tr key={day.date}>
                    <td>{day.date}</td>
                    <td>{day.total_orders}</td>
                    <td>{day.delivered_orders}</td>
                    <td>{formatMoney(day.gross_sales_minor)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        </div>
      ) : (
        <div className="empty-state">
          <h3>Loading dashboard</h3>
          <p>The overview aggregates orders, ledger rows, and rider availability in one response.</p>
        </div>
      )}
    </section>
  );
}
